services:
  match-be:
    build: .
    container_name: match-be
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/match-db
      SPRING_DATASOURCE_USERNAME: matchuser
      SPRING_DATASOURCE_PASSWORD: matchpass
  mysql:
    image: mysql:8.0
    container_name: mysql-match
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: match-db
      MYSQL_USER: matchuser
      MYSQL_PASSWORD: matchpass
    ports:
      - "3306:3306"
    volumes:
      - match_data:/var/lib/mysql

volumes:
  match_data: